django_orm/urls.py
from django.contrib import admin
from debug_toolbar.toolbar import debug_toolbar_urls

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('student/', include('student.urls', namespace='student'))
] + debug_toolbar_urls()

student/urls.py
from django.urls import path
from . import views

app_name = 'student'

urlpatterns = [
    path('', views.student_list, name='student_data'),
    path('and/', views.student_list_and, name='student_data_and'),
    path('union/', views.student_list_union, name='student_data_union'),
    path('not/', views.student_list_not, name='student_data_not'),
    path('select/', views.student_list_select, name='student_data_select'),
    path('raw/', views.student_list_raw, name='student_data_raw'),
    path('raw_sql/', views.student_list_raw_sql, name='student_data_raw_sql'),
    path('atomic/', views.student_list_atomic, name='student_data_atomic'),
    path('aggregate/', views.student_list_aggregate, name='student_data_aggregate'),
    path('delete/', views.student_delete, name='student_data_delete')
]

student/models.py
from django.db import models
from django.utils import timezone

# Model Tasks 1-5
#####################################

class Teacher(models.Model):

    firstname = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)

    def __str__(self):
        return self.firstname

class Student(models.Model):

    firstname = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    age = models.IntegerField()
    classroom = models.IntegerField()
    teacher = models.CharField(max_length=100)

    def __str__(self):
        return self.firstname

######################################

# Proxy models
# Change the behavior of a model
# Proxy models operate on the original model
class BookContent(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

class BookOrders(BookContent):
    class Meta:
        proxy = True
        ordering = ["created"]

    def created_on(self):
        return timezone.now() - self.created


# Multi table model inheritance
# Every model is a model all by itself
# One to one link is created automatically
class Books(models.Model):
    title = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)

class ISBN(Books):
    books_ptr = models.OneToOneField(
        Books, on_delete=models.CASCADE,
        parent_link=True,
        primary_key=True,
    )
    ISBN = models.TextField()


# Abstract Model
# Used when you have common information needed for number of other models
class BaseItem(models.Model):
    title = models.CharField(max_length=255)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True
        ordering = ["title"]

class ItemA(BaseItem):
    content = models.TextField()

    class Meta(BaseItem.Meta):
        ordering = ["-created"]

class ItemB(BaseItem):
    file = models.FileField(upload_to="files")

class ItemC(BaseItem):
    file = models.FileField(upload_to="images")

class ItemD(BaseItem):
    slug = models.SlugField(max_length=255, unique=True)


# Foreign key deletion contstraint
class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Manufacturer(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Warranty(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=255, null=True, blank=True)
    price = models.IntegerField(null=True, blank=True)
    category = models.ForeignKey(Category, null=True, blank=True, on_delete=models.SET_NULL, related_name="product_category")
    manufacturer = models.ForeignKey(Manufacturer, null=True, blank=True, on_delete=models.CASCADE, related_name="product_manufacturer")
    warranty = models.ForeignKey(Warranty, null=True, blank=True, on_delete=models.PROTECT, related_name="product_warranty")

    def __str__(self):
        return f"{self.name} - {self.category}"

# Using SET_NULL will set the value of the "category "field to null if the value of the foreignKey is deleted on the parent table.

# Using SET_DEFAULT will set the value of the field to the set default value when the foreignKey is deleted.

# Using CASCADE will also delete the value of "manufacturer" when the foreignKey is deleted.

# using PROTECT will not allow the deletion of foreignKey unless the related objects are already deleted.

# using RESTRICT is the same with PROTECT.

# using SET will set the value of the field based on the returned value of the function you specify to use.

# using DO_NOTHING will do nothing if the foreignKey is deleted.

student/forms.py
from django import forms

class ClassroomUpdateForm(forms.Form):
	studentone = forms.CharField(label="studentone", max_length=20)
	studenttwo = forms.CharField(label="studenttwo", max_length=20)
	classroom = forms.IntegerField(label="classroom")


class DeleteStudentForm(forms.Form):
	studentid = forms.IntegerField(label="studentid")

student/views.py
from .models import (
    Product,
    Student,
    Teacher,
)
from django.db import (
    connection,
    transaction
)
from django.db.models import (
    Avg,
    Max,
    Min,
    Q,
    Sum,
)
from django.shortcuts import render
from .forms import (
    ClassroomUpdateForm,
    DeleteStudentForm
)


# Part 2 OR query
#################################################################
def student_list_(request):

    posts = Student.objects.all()

    print(">>> Raw queryset")
    print(posts)

    print(">>> Raw SQL query")
    print(posts.query)

    print(">>> Execution details")
    print(connection.queries)

    return render(request, "output.html", {"posts":posts})

def student_list(request):
    # This query use the "|" symbol as "OR"
    # posts = Student.objects.filter(surname__startswith='Bautista') | Student.objects.filter(surname__startswith='Doe')

    # It can be simplified using "Q" objects together with the "|" symbol as OR
    posts = Student.objects.filter(Q(surname__startswith="Bautista") | Q(surname__startswith="Doe"))

    # Use can use tilde symbol "~" as not together with the "Q" object
    not_posts = Student.objects.filter(Q(surname__startswith="Bautista") | ~Q(surname__startswith="Doe"))

    print(posts)
    print(connection.queries)

    context = {
        "posts": posts,
        "not_posts": not_posts
    }

    return render(request, "output.html", context)


# Part 3 AND query
#################################################################
def student_list_and(request):
    # This query use the "&" symbol as "AND"
    # and_post = Student.objects.filter(classroom=3) & Student.objects.filter(firstname__startswith='Jane')

    # It can be simplified using "Q" objects together with the "&" symbol as AND
    and_post = Student.objects.filter(Q(classroom=3) & Q(firstname__startswith="Jane"))

    print(and_post)
    print(connection.queries)

    context = {
        "and_post": and_post
    }

    return render(request, "output.html", context)


# Part 4 UNION query
#################################################################
def student_list_union(request):
    # Union is used to combine the results of two select query
    # Union remove duplicates from the two combined query
    union_post = Student.objects.all().values_list("firstname").union(Teacher.objects.all().values_list("firstname"))

    print(union_post)
    print(connection.queries)

    context = {
        "union_post": union_post
    }

    return render(request, "output.html", context)


# Part 5 NOT query
#################################################################
def student_list_not(request):
    # You can use exclude and "&" symbol to create complex not query
    # not_post = Student.objects.exclude(surname__startswith="Bautista") & Student.objects.exclude(age__gt=23)

    # You can also simplify it using tilde symbol "~" as NOT together with the "Q" object
    not_post = Student.objects.filter(~Q(surname__startswith="Bautista") & ~Q(age__gt=23))

    print(not_post)
    print(connection.queries)

    context = {
        "not_post": not_post
    }

    return render(request, "output.html", context)


# Part 6 Select & Output Individual Fields
#################################################################
def student_list_select(request):
    # Use "only" to get specific fields from the table
    select_post = Student.objects.filter(classroom=1).only("firstname", "age")

    print(select_post)
    print(connection.queries)

    context = {
        "select_post": select_post
    }

    return render(request, "output.html", context)


# Part 7 Raw SQL queries
#################################################################
def student_list_raw(request):
    # Using Django ORM
    # all_post = Student.objects.all()

    # Using "raw" to perform raw sql queries
    raw_post = Student.objects.raw("SELECT * FROM student_student WHERE age=26")

    print(raw_post)
    print(connection.queries)

    context = {
        "raw_post": raw_post
    }

    return render(request, "output.html", context)


# Part 8 Simple Bypassing ORM
#################################################################
def dict_fetchall(cursor):
    """Helper function for converting the result of query to a dict"""
    desc = cursor.description
    return [
        dict(zip([col[0] for col in desc], row))
        for row in cursor.fetchall()
    ]

def student_list_raw_sql(request):
    # This will allow you to use the cursor object
    cursor = connection.cursor()

    # This is where you define your SQL query
    cursor.execute("SELECT * FROM student_student WHERE age > 23")

    # Output the data using helper function
    r = dict_fetchall(cursor)

    # Alternative method
    # r = cursor.fetchall()

    print(r)
    print(connection.queries)

    context = {
        "raw_sql_count": r
    }

    return render(request, "output.html", context)


# Part 13 Transaction Atomicity
#################################################################
def student_list_atomic(request):
    all_student = Student.objects.all()
    students = []
    error = ""

    print(all_student)
    print(connection.queries)

    if request.method == "POST":
        form = ClassroomUpdateForm(request.POST)

        if form.is_valid() == True:
            student_one = form.cleaned_data["studentone"]
            student_two = form.cleaned_data["studenttwo"]
            classroom = form.cleaned_data["classroom"]

            students = [student_one, student_two]
        else:
            form = ClassroomUpdateForm()

    if students:
        try:
            # Used transaction.atomic to guarantee that either all of the transaction succeeds or none of it does.
            with transaction.atomic():
                for student in students:
                    student_record = Student.objects.get(firstname=student.title())
                    student_record.classroom = classroom
                    student_record.save()
        except:
            error = "An exception occurred"

    context = {
        "all_student": all_student,
        "error": error
    }

    return render(request, "output.html", context)


# Part 15 Aggregation
#################################################################
def student_list_aggregate(request):

    product_data = Product.objects.aggregate(total=Sum("price"), mini=Min("price"),
                                             maxi=Max("price"), aveg=Avg("price"))

    print(product_data)
    print(connection.queries)

    context = {
        "product_data": product_data,
    }

    return render(request, "output.html", context)


def student_delete(request):

    all_student_rows = Student.objects.all()
    message = ""

    if request.method == "POST":
        form = DeleteStudentForm(request.POST)

        if form.is_valid() == True:
            studentid = form.cleaned_data["studentid"]
            try:
                Student.objects.get(pk=studentid).delete()
                message = "Successfully deleted"
            except:
                message = "Something went wrong"
        else:
            form = DeleteStudentForm()

    context = {
        "all_student_rows": all_student_rows,
        "message": message
    }

    return render(request, "output.html", context)

student/templates/output.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Django ORM</title>
</head>
<body>
    {% if posts %}
        <h4>Using "Q" objects together with the "|" symbol as OR</h4>
        <p>{{posts}}</p>
    {% endif %}

    {% if not_posts %}
        <h4>Using tilde symbol "~" as not together with the "Q" object</h4>
        <p>{{not_posts}}</p>
    {% endif %}

    {% if and_post %}
        <h4>Using "Q" objects together with the "&" symbol as AND</h4>
        <p>{{and_post}}</p>
    {% endif %}

    {% if union_post %}
        <h4>Using "Union" to combine results from two select query</h4>
        <p>{{union_post}}</p>
    {% endif %}

    {% if not_post %}
        <h4>Using tilde symbol "~" as not together with the "Q" object</h4>
        <p>{{not_post}}</p>
    {% endif %}

    {% if select_post %}
        <h4>Using "only" to get specific fields</h4>
         {% for i in select_post %}
            <div>{{ i.firstname }} - {{ i.age }}</div>
        {% endfor %}
    {% endif %}

    {% if raw_post %}
        <h4>Using "raw" to perform raw SQL queries</h4>
        {% for i in raw_post %}
            <div>{{ i }}</div>
        {% endfor %}
    {% endif %}

    {% if raw_sql_count %}
        <h4>Performing raw SQL queries without using ORM</h4>
        <p>{{raw_sql_count}}</p>
    {% endif %}

    {% if raw_sql_count %}
        {% for i in raw_sql_count %}
            <div>{{ i.firstname }} - {{ i.age }}</div>
        {% endfor %}
    {% endif %}

    {% if all_student %}
        <form action="{% url 'student:student_data_atomic' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="studentone">Name:</label>
                <input type="text" id="studentone" maxlength="20" name="studentone" value="{{ studentone }}" required>
            </div>
            <div class="mb-3">
                <label for="studenttwo">Name:</label>
                <input type="text" id="studenttwo" maxlength="20" name="studenttwo" value="{{ studenttwo }}" required>
            </div>
            <div class="mb-3">
                <label for="classroom">Classroom:</label>
                <input type="number" id="classroom" name="classroom" value="{{ classroom }}" required>
            </div>
            <div class="text-center">
                <input type="submit" value="Save">
            </div>
        </form>

        {% for i in all_student %}
            <div>{{ i.firstname }} {{ i.surname }} - Classroom {{ i.classroom }}</div>
        {% endfor %}
    {% endif %}

    {% if error %}
        <p>{{ error }}</p>
    {% endif %}

    {% if product_data %}
        <h4>The total of all products is {{ product_data.total }}</h4>
        <h4>The lowest price is {{ product_data.mini }}</h4>
        <h4>The highest price is {{ product_data.maxi }}</h4>
        <h4>The average price is {{ product_data.aveg }}</h4>
    {% endif %}

    {% if all_student_rows %}
        <form action="{% url 'student:student_data_delete' %}" method="post">
            {% csrf_token %}
            <div class="mb-3">
                <label for="studentid">Student ID:</label>
                <input type="number" id="studentid" name="studentid" value="{{ studentid }}" required>
            </div>
            <div class="text-center">
                <input type="submit" value="Delete">
            </div>
        </form>

        {% for i in all_student_rows %}
            <div>{{ i.id }} - {{ i.firstname }} {{ i.surname }} - Classroom {{ i.classroom }}</div>
        {% endfor %}
    {% endif %}

    {% if message %}
        <p>{{ message }}</p>
    {% endif %}
</body>
</html>